### ISSUE TITLE
Load ROM via URL, from input field or via query param

### ISSUE THREAD

**Issue by dangrussell** [andychase/gbajs2#8]
Allow users to enter a URL that points to a ROM to load.

Users on mobile may have an easier time pasting in a link to a file on Dropbox or a personal server than browsing their device's file system. Same could be done for the save.

Also, allow the ROM URL to passed in via a URL query parameter. This would enable users to bookmark or "Add to Homescreen" an instance of GBA.js that would boot up that game right away.  An additional URL parameter could also load a save.

**Comment by Qaena** [comment]
Is this possible with pure javascript? Adding the function is simple enough, but I kept running into cors issues from any external domain url.

**Comment by KIPAL999** [comment]
可以通过XMLHttpRequest()来指定url，从服务器端引入并加载rom即可

**Comment by andychase** [comment]
Similar to #24 and I put some sample code in there.

I’m open to merging a patch with this feature in it

**Comment by andychase** [comment]
@KIPAL999 CORS would still apply to that.

@Qaena yeah it’s a good point, if you are thinking of hotlinking files. Perhaps a better solution would be to use local storage to cache the rom so that it boots up if you re-load the page. Or re-host this website with the patch in #24 and your file included in the site.

There are websites already with illegally hosted commercial roms so I would assume just using those would be easier.

Another solution would be to make a proxy server that can download the CORS protected files and reserve them with cors.
